### ISSUE TITLE
Alternating elements and text raises exception

### ISSUE THREAD

**Issue by westbaystars** [xinz/sax_map#12]
I'm not sure if this problem is in `sax_map` or `saxy`, but XML such as the following is failing:

```elixir
iex(1)> xml="""
...(1)> <person id="test-person">
...(1)> <note id="abc123" lang="en" date="2018-11-13" type="general" format="html" summary="Example" status="approved" source="https://sample.com/">
...(1)> <DIV>
...(1)> <P>This is an example.</P>
...(1)> <P>Source: <A href="https://sample.com/article1.html" target="_blank" rel="noopener">Sample 1</A>, <A href="https://sample.com/article2.html" target="_blank" rel="noopener">Sample 2</A>, <A href="https://article3.html" target="_blank" rel="noopener">Article 3</A>
...(1)> </P>
...(1)> <P>
...(1)> <SMALL/>
...(1)> </P>
...(1)> </DIV>
...(1)> </note>
...(1)> </person>
...(1)> """
"<person id=\"test-person\">\n<note id=\"abc123\" lang=\"en\" date=\"2018-11-13\" type=\"general\" format=\"html\" summary=\"Example\" status=\"approved\" source=\"https://sample.com/\">\n<DIV>\n<P>This is an example.</P>\n<P>Source: <A href=\"https://sample.com/article1.html\" target=\"_blank\" rel=\"noopener\">Sample 1</A>, <A href=\"https://sample.com/article2.html\" target=\"_blank\" rel=\"noopener\">Sample 2</A>, <A href=\"https://article3.html\" target=\"_blank\" rel=\"noopener\">Article 3</A>\n</P>\n<P>\n<SMALL/>\n</P>\n</DIV>\n</note>\n</person>\n"
iex(2)> SAXMap.from_string(xml, ignore_attribute: {false, "@"})
** (FunctionClauseError) no function clause matching in SAXMap.Handler.list_to_map/2

    The following arguments were given to SAXMap.Handler.list_to_map/2:

        # 1
        ", "

        # 2
        %{
          "A" => %{
            "@href" => "https://article3.html",
            "@rel" => "noopener",
            "@target" => "_blank",
            "content" => "Article 3"
          }
        }

    Attempted function clauses (showing 3 out of 3):

        defp list_to_map([], prepared)
        defp list_to_map([item | rest], prepared) when is_map(item)
        defp list_to_map([{key, value} | rest], prepared)

    (sax_map 1.3.0) lib/handler.ex:234: SAXMap.Handler.list_to_map/2
    (sax_map 1.3.0) lib/handler.ex:182: SAXMap.Handler.handle_event/3
    (saxy 1.6.0) lib/saxy/emitter.ex:16: Saxy.Emitter.emit/3
    (saxy 1.6.0) lib/saxy/emitter.ex:7: Saxy.Emitter.emit/4
    (saxy 1.6.0) lib/saxy/parser/builder.ex:1195: Saxy.Parser.Binary.close_tag_name/7
    (saxy 1.6.0) lib/saxy.ex:197: Saxy.parse_string/4
    iex:2: (file)
```

To confirm, I added the following `list_to_map` optional function to `handler.ex`:

```diff
    defp list_to_map([], prepared) do
      prepared
    end

+   defp list_to_map(item, prepared) when is_binary(item) do
+     throw("Got a string")
+   end
  
    defp list_to_map([item | rest], prepared) when is_map(item) do
```

The `Got a string` exception was thrown on the final `", ", <A....` `item` and `prepared`. The only way I was able to get this XML to parse was to remove **all** links. It failed even with only one.

I'm not sure where to start debugging this. Is `saxy` sending the wrong event? I don't see `list_to_map` called anywhere other than while handling elements by way of `format_key_value_pairs`. Because this is `content`, it shouldn't be here, should it?

Any hints would be appreciated for where to start.

Take care.

**Comment by xinz** [comment]
Hi @westbaystars , when you process the above mentioned XML data, what's your expectation to get the transferred map?

```
<person id="test-person">
  <note id="abc123" lang="en" date="2018-11-13" type="general" format="html" summary="Example" status="approved" source="https://sample.com/">
    <DIV>
       <P>This is an example.</P>
       <P>
        Source:
        <A href="https://sample.com/article1.html" target="_blank" rel="noopener">Sample 1</A>
          ,
        <A href="https://sample.com/article2.html" target="_blank" rel="noopener">Sample 2</A>
          ,
        <A href="https://article3.html" target="_blank" rel="noopener">Article 3</A>
      </P>
      <P>
        <SMALL/>
      </P>
    </DIV>
  </note>
</person>
```

**Comment by westbaystars** [comment]
Hi @xinz ,

I've traced the problem down to the `list_to_map` function on line 238:

```elixir
  defp list_to_map([item | rest], prepared) when is_map(item) do
    [{key, value}] = Map.to_list(item)
    current_value = Map.get(prepared, key)
    prepared = put_or_concat_to_map(current_value, prepared, key, value)
    list_to_map(rest, prepared)
  end
```

`rest`, in this case, is a `binary`. I'm about to change it to `[%{"content" => rest}]` on line 242 and see what I get. Once I see how that works, I may have a patch for you.

**Comment by westbaystars** [comment]
Hi @xinz,

Ah, that was promising. It now process the last link, so I get this:

```elixir
{:ok,
 %{
   "person" => %{
     "@id" => "test-person",
     "content" => %{
       "note" => %{
         "@date" => "2018-11-13",
         "@format" => "html",
         "@id" => "abc123",
         "@lang" => "en",
         "@source" => "https://sample.com/",
         "@status" => "approved",
         "@summary" => "Example",
         "@type" => "general",
         "content" => %{
           "DIV" => %{
             "content" => %{
               "P" => [
                 %{"content" => "This is an example."},
                 %{
                   "content" => %{
                     "A" => %{
                       "@href" => "https://article3.html",
                       "@rel" => "noopener",
                       "@target" => "_blank",
                       "content" => "Article 3"
                     },
                     "content" => "\n          ,\n        "
                   }
                 },
                 %{"content" => %{"SMALL" => %{"content" => nil}}}
               ]
             }
           }
         }
       }
     }
   }
 }}
```

The comma and `Enter` content should be before the `<A ...` element. And, of course, the other two links should be there as well.

I'm not sure why only the last element is being processed. Will continue tracing.

**Comment by xinz** [comment]
Thanks, could you please share your expectation result to the above case? so I can evaluate and investigate on it.

**Comment by westbaystars** [comment]
Hi @xinz,

Now that I have an output that is close, I guess that this is what I'm expecting to see:

```elixir
{:ok,
 %{
   "person" => %{
     "@id" => "test-person",
     "content" => %{
       "note" => %{
         "@date" => "2018-11-13",
         "@format" => "html",
         "@id" => "abc123",
         "@lang" => "en",
         "@source" => "https://sample.com/",
         "@status" => "approved",
         "@summary" => "Example",
         "@type" => "general",
         "content" => %{
           "DIV" => %{
             "content" => %{
               "P" => [
                 %{"content" => [
                   "This is an example.",
                   %{
                     "A" => %{
                       "@href" => "https://article1.html",
                       "@rel" => "noopener",
                       "@target" => "_blank",
                       "content" => "Sample 1"
                     }
                   },
                   ",\n",
                   %{
                     "A" => %{
                       "@href" => "https://article2.html",
                       "@rel" => "noopener",
                       "@target" => "_blank",
                       "content" => "Sample 2"
                     }
                   },
                   ",\n",
                   %{
                     "A" => %{
                       "@href" => "https://article3.html",
                       "@rel" => "noopener",
                       "@target" => "_blank",
                       "content" => "Article 3"
                     }
                   }
                   %{"SMALL" => %{"content" => nil}}
                 ]
               ]
             }
           }
         }
       }
     }
   }
 }}
```

Both the `A` tags and text are `content` under the `P`, therefore, they should be in a single array. At least to my thinking. What do you think?

I should probably make the sample article titles more consistent. Oh, and I just noticed that the third one is an invalid URL. Let's change the third anchor tag like this:

```elixir
        <A href="https://sample.com/article3.html" target="_blank" rel="noopener">Sample 3</A>
```

**Comment by westbaystars** [comment]
Hi @xinz,

Oh, the way I got the exception to stop was to add:

```diff
    defp list_to_map([], prepared) do
      prepared
    end

+   defp list_to_map(value, prepared) when is_binary(value) do
+     list_to_map([%{"content" => value}], prepared)
+   end
+ 
    defp list_to_map([item | rest], prepared) when is_map(item) do
```

But, as noted, the order is wrong and other elements are not added.

**Comment by xinz** [comment]
Thanks, I will take this issue.

**Comment by westbaystars** [comment]
Thank you.

**Comment by xinz** [comment]
> Both the A tags and text are content under the P, therefore, they should be in a single array. At least to my thinking. What do you think?

Hi @westbaystars, refer the above your mentioned result, I don't think put them into a list like `%{"content" => ["text content", %{}, "...", %{}, "...", etc]}` is convenient for the next read operation. 

here are my proposal for your use case(I only reserved the key XML data to process between `"text content"`(or naming `"text node"`) and child elements), please review:

Input:
```elixir
    xml = """
    <p>Source: <a href="test">link1</a>,<a href="test2">link2</a>,</p>
    """
```

Output:
```elixir
iex> SAXMap.from_string(xml)
{:ok,
 %{
   "p" => %{"a" => ["link1", "link2"], "text_content" => ["Source: ", ",", ","]}
 }}
iex> SAXMap.from_string(xml, ignore_attribute: {false, "@"})
{:ok,
 %{
   "p" => %{
     "content" => %{
       "a" => [
         %{"@href" => "test", "content" => "link1"},
         %{"@href" => "test2", "content" => "link2"}
       ],
       "text_content" => ["Source: ", ",", ","]
     }
   }
 }}
```

Input:
```elixir
    xml = """
    <p><a href="test">link1</a>,<a href="test2">link2</a>,</p>
    """
```

Output:
```elixir
iex> SAXMap.from_string(xml)
{:ok, %{"p" => %{"a" => ["link1", "link2"], "text_content" => [",", ","]}}}
iex> SAXMap.from_string(xml, ignore_attribute: {false, "@"})
{:ok,
 %{
   "p" => %{
     "content" => %{
       "a" => [
         %{"@href" => "test", "content" => "link1"},
         %{"@href" => "test2", "content" => "link2"}
       ],
       "text_content" => [",", ","]
     }
   }
 }}
```

There is a new added `"text_content"` key reserved to use in the returned map result, this change is still keep the original compatibility, WDYT?

**Comment by westbaystars** [comment]
Hmmm. Checking what would happen if the mixed text was replaced with `<span>...</span>` tags, that appears to be consistent.

```xml
<person id="test-person">
  <note id="abc123" lang="en" date="2018-11-13" type="general" format="html" summary="Example" status="approved" source="https://sample.com/">
    <DIV>
       <P>This is an example.</P>
       <P>
        <span>Source:</span>
        <A href="https://sample.com/article1.html" target="_blank" rel="noopener">Sample 1</A>
        <span>, </span>
        <A href="https://sample.com/article2.html" target="_blank" rel="noopener">Sample 2</A>
        <span>, </span>
        <A href="https://sample.com/article3.html" target="_blank" rel="noopener">Sample 3</A>
      </P>
    </DIV>
  </note>
</person>
```

Output:
```elixir
{:ok,
 %{
   "person" => %{
     "@id" => "test-person",
     "content" => %{
       "note" => %{
         "@date" => "2018-11-13",
         "@format" => "html",
         "@id" => "abc123",
         "@lang" => "en",
         "@source" => "https://sample.com/",
         "@status" => "approved",
         "@summary" => "Example",
         "@type" => "general",
         "content" => %{
           "DIV" => %{
             "content" => %{
               "P" => [
                 %{"content" => "This is an example."},
                 %{
                   "content" => %{
                     "A" => [
                       %{
                         "@href" => "https://sample.com/article1.html",
                         "@rel" => "noopener",
                         "@target" => "_blank",
                         "content" => "Sample 1"
                       },
                       %{
                         "@href" => "https://sample.com/article2.html",
                         "@rel" => "noopener",
                         "@target" => "_blank",
                         "content" => "Sample 2"
                       },
                       %{
                         "@href" => "https://sample.com/article3.html",
                         "@rel" => "noopener",
                         "@target" => "_blank",
                         "content" => "Sample 3"
                       }
                     ],
                     "span" => [
                       %{"content" => "Source:"},
                       %{"content" => ", "},
                       %{"content" => ", "}
                     ]
                   }
                 }
               ]
             }
           }
         }
       }
     }
   }
 }}
```

Recreating the order that things come in doesn't appear to be possible. But gathering all of the information is there, which I believe is the core purpose of this utility. 

Yes, this is a good solution, as it doesn't lose any information. I'm mostly interested in extracting the links rather than the text around them. And being able to get all of the links without an exception is the most important.

Thank you for your time diving into this.

Take care.

**Comment by xinz** [comment]
Consider naming consistency, I prefer to use  `"content"` instead of `"text_content"` as the key name.

**Comment by xinz** [comment]
My local changed code out put the same result as your previous one, I will submit it later, thanks your feedback.

**Comment by westbaystars** [comment]
> Consider naming consistency, I prefer to use `"content"` instead of `"text_content"` as the key name.

I agree. That is more consistent. 👍

**Comment by xinz** [comment]
Hi @westbaystars , could you please try the [fix-text](https://github.com/xinz/sax_map/tree/fix-text) branch for your use case?

**Comment by westbaystars** [comment]
For the given test data:
```xml
<person id="test-person">
  <note id="abc123" lang="en" date="2018-11-13" type="general" format="html" summary="Example" status="approved" source="https://sample.com/">
    <DIV>
       <P>This is an example.</P>
       <P>
        Source:
        <A href="https://sample.com/article1.html" target="_blank" rel="noopener">Sample 1</A>
          ,
        <A href="https://sample.com/article2.html" target="_blank" rel="noopener">Sample 2</A>
          ,
        <A href="https://sample.com/article3.html" target="_blank" rel="noopener">Sample 3</A>
      </P>
      <P>
        <SMALL/>
      </P>
    </DIV>
  </note>
</person>
```

It results in:

```exist
{:ok,
 %{
   "person" => %{
     "@id" => "test-person",
     "content" => %{
       "note" => %{
         "@date" => "2018-11-13",
         "@format" => "html",
         "@id" => "abc123",
         "@lang" => "en",
         "@source" => "https://sample.com/",
         "@status" => "approved",
         "@summary" => "Example",
         "@type" => "general",
         "content" => %{
           "DIV" => %{
             "content" => %{
               "P" => [
                 %{"content" => "This is an example."},
                 %{
                   "content" => %{
                     "A" => [
                       %{
                         "@href" => "https://sample.com/article1.html",
                         "@rel" => "noopener",
                         "@target" => "_blank",
                         "content" => "Sample 1"
                       },
                       %{
                         "@href" => "https://sample.com/article2.html",
                         "@rel" => "noopener",
                         "@target" => "_blank",
                         "content" => "Sample 2"
                       },
                       %{
                         "@href" => "https://sample.com/article3.html",
                         "@rel" => "noopener",
                         "@target" => "_blank",
                         "content" => "Sample 3"
                       }
                     ],
                     "content" => ["\n        Source:\n        ",
                      "\n          ,\n        ", "\n          ,\n        "]
                   }
                 },
                 %{"content" => %{"SMALL" => %{"content" => nil}}}
               ]
             }
           }
         }
       }
     }
   }
 }}
```

Yes, I believe that that is expected. And most importantly, there is no longer an exception throw.

Close #13

**Comment by xinz** [comment]
Thanks very much for your confirmation, I will make a release version of hex.pm.

**Comment by xinz** [comment]
[1.4.0](https://hex.pm/packages/sax_map/1.4.0) is released now, thanks.

**Comment by westbaystars** [comment]
Thank you.

❤️💛💚💙💜
